version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8080:80
  mysql-db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33006:3306
    volumes:
      - ./mysql/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
  phpmyadmin:
    #image: phpmyadmin/phpmyadmin
    image: arm64v8/phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql-db
